apiVersion: v2
description: An automated observability platform for cloud-native developers.
name: deepflow
engine: gotpl
type: application
version: 0.1.001
appVersion: "6.1.1"
kubeVersion: ">=1.16.0-0"
sources:
  - https://github.com/deepflowys/deepflow
home: https://github.com/deepflowys/deepflow
keywords:
  - deepflow
dependencies:
- name: deepflow-agent
  repository: ""
  version: '*.*.*'
  condition: deepflow-agent.enabled
- name: clickhouse
  repository: ""
  version: '*.*.*'
- name: mysql
  repository: ""
  version: '*.*.*'
- name: grafana
  version: "6.32.*"
  repository: https://grafana.github.io/helm-charts
  condition: grafana.enabled