name: dhcp_port
public_name: DHCPPort

cache_diffbase:
  enabled: true
  fields:
    - name: Name
      type: string
    - name: RegionLcuuid
      type: string
      db_field_name: Region
    - name: AZLcuuid
      type: string
      db_field_name: AZ
    - name: VPCLcuuid
      type: string
      ref: VPC
      db_field_name: VPCID

cache_tool:
  enabled: true
  fields:
  - name: lcuuid
    public_name: Lcuuid
    type: string
    is_validation_field: true
  - name: id
    public_name: ID
    type: int
  - name: name
    public_name: Name
    type: string
  - name: regionID
    public_name: Region
    type: int
    ref: Region
  - name: azID
    public_name: AZ
    type: int
    ref: AZ
  - name: vpcID
    public_name: VPCID
    type: int
