name: host
public_name: Host

cache_diffbase:
  enabled: true
  fields:
    - name: Name
      type: string
    - name: IP
      type: string
    - name: Hostname
      type: string
    - name: HType
      type: int
    - name: VCPUNum
      type: int
    - name: MemTotal
      type: int
    - name: ExtraInfo
      type: string
    - name: RegionLcuuid
      type: string
      db_field_name: Region
    - name: AZLcuuid
      type: string
      db_field_name: AZ

cache_tool:
  enabled: true
  fields:
  - name: lcuuid
    public_name: Lcuuid
    type: string
    is_validation_field: true
  - name: id
    public_name: ID
    type: int
  - name: name
    public_name: Name
    type: string
  - name: regionID
    public_name: Region
    type: int
    ref: Region
  - name: azID
    public_name: AZ
    type: int
    ref: AZ
  - name: ip
    public_name: IP
    type: string
  key_fields:
  - name: ip
    public_name: IP
    type: string
