name: network
public_name: Network
cache_tool:
  enabled: true
  fields:
  - name: lcuuid
    public_name: Lcuuid
    type: string
    is_validation_field: true
  - name: id
    public_name: ID
    type: int
  - name: name
    public_name: Name
    type: string
  - name: vpcID
    public_name: VPCID
    type: int
