name: pod_group
public_name: PodGroup

cache_diffbase:
  enabled: true
  fields:
    - name: Name
      type: string
    - name: Label
      type: string
    - name: PodNum
      type: int
    - name: Type
      type: int
    - name: Metadata
      type: string
      db_type: bytes
      need_hide: true
    - name: MetadataHash
      type: string
    - name: Spec
      type: string
      db_type: bytes
      need_hide: true
    - name: SpecHash
      type: string
    - name: RegionLcuuid
      type: string
      db_field_name: Region
    - name: AZLcuuid
      type: string
      db_field_name: AZ
    - name: SubDomainLcuuid
      type: string
      db_field_name: SubDomain
    - name: NetworkMode
      type: int

cache_tool:
  enabled: true
  fields:
  - name: lcuuid
    public_name: Lcuuid
    type: string
    is_validation_field: true
  - name: id
    public_name: ID
    type: int
  - name: name
    public_name: Name
    type: string
  - name: gType
    public_name: Type
    type: int
    db_field_name: Type
  - name: regionID
    public_name: RegionID
    type: int
    ref: Region
    db_field_name: Region
  - name: azID
    public_name: AZID
    type: int
    ref: AZ
    db_field_name: AZ
  - name: podNamespaceID
    public_name: PodNamespaceID
    type: int
  - name: podClusterID
    public_name: PodClusterID
    type: int
