name: vinterface
public_name: VInterface
cache_tool:
  enabled: true
  fields:
  - name: lcuuid
    public_name: Lcuuid
    type: string
    is_validation_field: true
  - name: id
    public_name: ID
    type: int
  - name: name
    public_name: Name
    type: string
  - name: ifType
    public_name: Type
    type: int
  - name: index
    public_name: Index
    type: int
  - name: mac
    public_name: Mac
    type: string
  - name: regionID
    public_name: RegionID
    type: int
    ref: Region
    db_field_name: Region
  - name: networkID
    public_name: NetworkID
    type: int
  - name: vpcID
    public_name: VPCID
    type: int
  - name: deviceType
    public_name: DeviceType
    type: int
  - name: deviceID
    public_name: DeviceID
    type: int
  - name: deviceName
    public_name: DeviceName
    type: string
    is_custom: true
  has_extension: true
  collection_extension: true
