name: vrouter
public_name: VRouter

cache_diffbase:
  enabled: true
  fields:
    - name: Name
      type: string
    - name: Label
      type: string
    - name: VPCLcuuid
      type: string
      ref: VPC
      db_field_name: VPCID
    - name: RegionLcuuid
      type: string
      db_field_name: Region

cache_tool:
  enabled: true
  fields:
  - name: lcuuid
    public_name: Lcuuid
    type: string
    is_validation_field: true
  - name: id
    public_name: ID
    type: int
  - name: name
    public_name: Name
    type: string
  - name: regionID
    public_name: RegionID
    type: int
    ref: Region
    db_field_name: Region
  - name: vpcID
    public_name: VPCID
    type: int
  - name: gwLaunchServer
    public_name: GWLaunchServer
    type: string
