[package]
name = "public-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
cfg-if.workspace = true
proc-macro2 = "1.0"
public-derive-internals.workspace = true
quote = "1.0"
syn = "2.0"

[dev-dependencies]
trybuild = "1.0"
