# Default values for mysql.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  podAntiAffinityLabelSelector: []
  podAntiAffinityTermLabelSelector: []
  podAffinityLabelSelector: []
  podAffinityTermLabelSelector: []
  nodeAffinityLabelSelector: []
  nodeAffinityTermLabelSelector: []

replicas: 1

image:
  repository: mysql
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "8.0.26"

hostNetwork: "false"
dnsPolicy: ClusterFirst
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
password: deepflow

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
storageConfig:
  ## persistentVolumeClaim/hostPath
  type: persistentVolumeClaim
  hostPath: /opt/deepflow-mysql
  persistence:
    storageClass: "-"
    annotations:
      "helm.sh/resource-policy": keep
    # existingClaim: your-claim-pvc-name
    accessMode: ReadWriteOnce
    size: 50Gi 
    
externalMySQL:
  enabled: false
  hostIP: 192.168.1.1
  port: 30130

service:
  ## Configuration for Clickhouse service
  ##
  annotations: {}
  labels: {}
  clusterIP: ""

  ## Port for Clickhouse Service to listen on
  ##

  ports:
  - name: tcp
    port: 30130
    targetPort: 30130
    nodePort: 
    protocol: TCP
  ## Additional ports to open for server service
  additionalPorts: []

  externalIPs: []
  loadBalancerIP: ""
  loadBalancerSourceRanges: []

  ## Denotes if this Service desires to route external traffic to node-local or cluster-wide endpoints
  ## must be Local
  externalTrafficPolicy: Cluster

  ## Service type
  ##
  type: ClusterIP


resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

podAntiAffinityLabelSelector: []
podAntiAffinityTermLabelSelector: []
podAffinityLabelSelector: []
podAffinityTermLabelSelector: []
nodeAffinityLabelSelector: []
nodeAffinityTermLabelSelector: []

