[package]
name = "enterprise-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags.workspace = true
public.workspace = true
serde.workspace = true
strum = { version = "0.27", features = ["derive"] }
strum_macros = "0.27"
