[package]
name = "l7-log-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
l7-log.workspace = true
proc-macro2 = "1.0"
quote = "1.0"
syn = "2.0"

[dev-dependencies]
public.workspace = true
trybuild = "1.0"