kind: ConfigMap
apiVersion: v1
metadata:
  name: deepflow-agent
  namespace: yunshan-deepflow
data:
  deepflow-agent.yaml: |-
    controller-ips:
    - 10.1.4.1
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: deepflow-agent
  namespace: yunshan-deepflow
spec:
  selector:
    matchLabels:
      app: deepflow-agent
  template:
    metadata:
      annotations:
        container.apparmor.security.beta.kubernetes.io/deepflow-agent: unconfined
      name: deepflow-agent
      namespace: yunshan-deepflow
      labels:
        app: deepflow-agent
    spec:
      hostNetwork: true
      hostPID: true
      containers:
        - name: deepflow-agent
          image: deepflow-agent:latest
          imagePullPolicy: Always
          securityContext:
            privileged: true
          volumeMounts:
            - name: sys-kernel-debug
              mountPath: /sys/kernel/debug
            - name: deepflow-agent-conf
              mountPath: /etc/deepflow-agent
            - name: logs
              mountPath: /var/log/deepflow-agent/
              subPath: ""
      volumes:
        - name: sys-kernel-debug
          hostPath:
            path: /sys/kernel/debug
        - name: deepflow-agent-conf
          configMap:
            name: deepflow-agent
        - name: logs
          hostPath:
            type: DirectoryOrCreate
            path: /var/log/deepflow-agent
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deepflow-agent-role
rules:
- apiGroups: [""]
  resources:
  - nodes
  - namespaces
  - configmaps
  - services
  - pods
  - replicationcontrollers
  - events
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources:
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions", "networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["route.openshift.io"]
  resources: ["routes"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deepflow-agent-view-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: yunshan-deepflow
roleRef:
  kind: ClusterRole
  name: deepflow-agent-role
  apiGroup: rbac.authorization.k8s.io
