apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: deepflow-agent
  namespace: yunshan-deepflow
spec:
  selector:
    matchLabels:
      app: deepflow-agent
  template:
    metadata:
      annotations:
        container.apparmor.security.beta.kubernetes.io/deepflow-agent: unconfined
      name: deepflow-agent
      namespace: yunshan-deepflow
      labels:
        app: deepflow-agent
    spec:
      dnsPolicy: ClusterFirst
      hostPID: true
      containers:
        - name: deepflow-agent
          image: deepflow-agent
          imagePullPolicy: Never
          securityContext:
            privileged: true
          readinessProbe:
            httpGet:
              path: /v1/ready/
              port: 38086
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /v1/health/
              port: 38086
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: sys-kernel-debug
              mountPath: /sys/kernel/debug
            - name: deepflow-agent-conf
              mountPath: /etc/deepflow-agent
            - name: logs
              mountPath: /var/log/deepflow-agent/
              subPath: ""
            - name: netns # required to access net namespace info
              mountPath: /var/run/netns
              mountPropagation: HostToContainer
      volumes:
        - name: sys-kernel-debug
          hostPath:
            path: /sys/kernel/debug
        - name: deepflow-agent-conf
          configMap:
            name: deepflow-agent-config
        - name: logs
          hostPath:
            type: DirectoryOrCreate
            path: /var/log/deepflow-agent
        - name: netns
          hostPath:
            path: /var/run/netns
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deepflow-agent-role
rules:
- apiGroups: [""]
  resources:
  - nodes
  - namespaces
  - configmaps
  - services
  - pods
  - replicationcontrollers
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources:
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions", "networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["route.openshift.io"]
  resources: ["routes"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deepflow-agent-view-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: yunshan-deepflow
roleRef:
  kind: ClusterRole
  name: deepflow-agent-role
  apiGroup: rbac.authorization.k8s.io
