on:
  push:
    branches:
      - package-rust-env
    paths:
      - 'agent/docker/DockerfileToFix.build'
      - 'agent/docker/DockerfileToFix-aarch64.build'
      - 'agent/docker/dockerfile-build-env'
      - 'agent/docker/dockerfile-build-env-aarch64'
  workflow_dispatch:
    inputs:
      ref:
        description: "Why trigger?"
        required: true
        type: string

name: build agent env

jobs:
  build_agent_env:
    name: build agent env
    runs-on: "cirun-aws-amd64-32c--${{ github.run_id }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: install docker
      #   run: |
      #     curl -fsSL https://get.docker.com | bash

      - name: docker version
        run: |
          docker version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: "ghcr.io"
          username: "${{ github.repository_owner }}"
          password: "${{ secrets.GHCR_PUSH_TOKEN }}"

      - name: Log in to ALIYUN Docker Registry
        uses: docker/login-action@v2
        with:
          registry: "${{ secrets.REGISTRY_ALIYUN_ADDR }}"
          username: "${{ secrets.REGISTRY_ALIYUN_USER }}"
          password: "${{ secrets.ALIYUN_DF_CLOUD_REGISTRY_PASSWORD }}"

      - name: Build and push deepflow agent env images
        uses: docker/build-push-action@v2
        with:
          context: agent
          push: true
          #file: agent/docker/DockerfileToFix.build
          file: agent/docker/dockerfile-build-env
          platforms: linux/amd64
          tags: |
            "ghcr.io/${{ github.repository_owner }}/rust-build:1.31"
            "ghcr.io/${{ github.repository_owner }}/rust-build:latest"
            "${{ secrets.REGISTRY_ALIYUN_ADDR }}/public/rust-build:1.31"
            "${{ secrets.REGISTRY_ALIYUN_ADDR }}/public/rust-build:latest"

  build_agent_env_arm64:
    name: build agent env arm64
    runs-on: "cirun-aws-arm64-32c--${{ github.run_id }}"
    steps:

      - name: Checkout
        uses: actions/checkout@v3
      # - name: install docker
      #   run: |
      #     curl -fsSL https://get.docker.com | bash

      - name: docker version
        run: |
          docker version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: "ghcr.io"
          username: "${{ github.repository_owner }}"
          password: "${{ secrets.GHCR_PUSH_TOKEN }}"

      - name: Log in to ALIYUN Docker Registry
        uses: docker/login-action@v2
        with:
          registry: "${{ secrets.REGISTRY_ALIYUN_ADDR }}"
          username: "${{ secrets.REGISTRY_ALIYUN_USER }}"
          password: "${{ secrets.ALIYUN_DF_CLOUD_REGISTRY_PASSWORD }}"

      - name: Build and push deepflow agent env image
        uses: docker/build-push-action@v2
        with:
          context: agent
          push: true
          #file: agent/docker/DockerfileToFix-aarch64.build
          file: agent/docker/dockerfile-build-env-aarch64
          platforms: linux/arm64
          tags: |
            "ghcr.io/${{ github.repository_owner }}/rust-build:1.31-arm64"
            "ghcr.io/${{ github.repository_owner }}/rust-build:latest-arm64"
            "${{ secrets.REGISTRY_ALIYUN_ADDR }}/public/rust-build:1.31-arm64"
            "${{ secrets.REGISTRY_ALIYUN_ADDR }}/public/rust-build:latest-arm64"
